name: portable-release-actions-workflow
# on:
#   # push:
#   #   # Sequence of patterns matched against refs/tags
#   #   tags:
#   #     - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
#   #     - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
permissions:
    contents: write
    
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: cygwin-portable-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v4

      - name: installer
        shell: cmd
        run: |
          curl -L -O "https://www.cygwin.com/setup-x86_64.exe" &&^
          dir

      - name: elevate
        shell: cmd
        run: |
          curl -L -J --output elevate.zip "https://github.com/jpassing/elevate/releases/download/1.0/elevate.zip" &&^
          7z.exe x elevate.zip &&^
          dir

      - shell: cmd
        run: |
          .\bin\x64\Release\Elevate.exe -wait reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f &&^
          .\bin\x64\Release\Elevate.exe -wait reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v ConsentPromptBehaviorAdmin /t REG_DWORD /d 0 /f &&^
          echo disabled
          
      - shell: cmd
        run: |
          setup-x86_64.exe ^
          --quiet-mode ^
          --root "%cd%\cygwin" ^ 
          --local-package-dir "%cd%\cygwin\.pkg-cache" ^
          --site "http://cygwin.mirrors.hoobly.com/" ^
          --delete-orphans ^
          --prune-install ^
          --upgrade-also ^
          --no-replaceonreboot ^
          --packages "openmpi,gcc-g++,gcc-core"
 
      - shell: cmd
        run: |
          setup-x86_64.exe ^
          --site "http://cygwin.mirrors.hoobly.com/" ^
          --no-admin ^
          --quiet-mode ^
          --arch x64 ^
          --packages libopenmpi-devel
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "cygwin"
          filename: "${{ env.targetZip }}"
            
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cygwin/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
