name: cygwin-action-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'
      
permissions:
    contents: write

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login -o igncr '{0}'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: gcc-g++ make

      - run: |
          echo $(pwd) && \
          ls && \
          cd '${{ github.workspace }}' && \
          ls && \
          g++ --version && \
          uname -a
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "C:/tools/cygwin"
          filename: "cygwin-${{ github.ref_name }}.zip"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "C:/tools/cygwin/cygwin-${{ github.ref_name }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
