name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
permissions:
    contents: write
    
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: cygwin-portable-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v4

      - name: installer
        shell: cmd
        run: |
          curl -L -J --output installer.exe "https://www.cygwin.com/setup-x86_64.exe" &&^
          dir
          
      - shell: cmd
        run: |
          set __COMPAT_LAYER=RUNASINVOKER
          installer.exe ^
          --quiet-mode ^
          --root "%cd%\cygwin" ^ 
          --arch x64 ^ --local-package-dir "%cd%\cygwin\packages" ^
          --prune-install ^
          --packages openmpi
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "cygwin"
          filename: "${{ env.targetZip }}"
            
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cygwin/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
